### Import Necessary Libraries

In [1]:
import numpy as np
import pandas as pd

#### Zero Array

In [3]:
zero_array=np.zeros((4,2),dtype=int)
zero_array

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

#### List to Array

In [6]:
L1=[1,2,'a','abc']
L1

[1, 2, 'a', 'abc']

In [7]:
arr1=np.array(L1)
print(arr1)

['1' '2' 'a' 'abc']


In [3]:
new_array=np.array([1,2,3,4,5,6,7,8,9])
new_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Find maximum, minimum, sum

In [7]:
new_array.max()

9

In [9]:
new_array.sum()

45

### Indexing & Slicing

- To find arr[m:n] the indexing starts from mth index and continues till (n-1) th index.

In [13]:
new_array[2]

3

In [14]:
new_array[2:7]

array([3, 4, 5, 6, 7])

### Reverse of an Array

In [16]:
new_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [31]:
new_array[::-2]

array([9, 7, 5, 3, 1])

In [35]:
new_array[8:1:-2]

array([9, 7, 5, 3])

### Mathematical Operations

#### Multiply each element by 2

In [19]:
new_array*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

#### Square each element

In [11]:
new_array**2

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

#### Find even numbers

In [22]:
new_array[new_array%2==0]

array([2, 4, 6, 8])

In [13]:
new_array%2==0

array([False,  True, False,  True, False,  True, False,  True, False])

#### Find elements greater than 5

In [24]:
new_array[new_array>5]

array([6, 7, 8, 9])

#### Count numbers divisible by 3

In [5]:
np.sum(new_array%3==0)

3

#### Two Dimentional Array

In [27]:
l2=[[20,30],[40,50]]
l2

[[20, 30], [40, 50]]

In [28]:
arr2=np.array(l2)
arr2

array([[20, 30],
       [40, 50]])

#### Three Dimentional Array

In [15]:
arr3=np.array([[[1,2],[3,4],[5,6]]])
arr3

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [31]:
arr4=np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]])
arr4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

#### Find the Shape, Dimension and number of elements of an Array

In [18]:
arr3

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [33]:
arr3.shape

(1, 3, 2)

In [34]:
arr3.ndim

3

In [35]:
arr3.size

6

#### Array Reshaping

In [21]:
new_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
array_reshape=new_array.reshape(3,3)
array_reshape

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
array_reshape.ndim

2

In [39]:
array_reshape.shape

(3, 3)

In [40]:
array_reshape_1=new_array.reshape(1,3,3)
array_reshape_1

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [41]:
array_reshape_1.shape

(1, 3, 3)

In [42]:
array_reshape_1.ndim

3

In [25]:
array_reshape_2=new_array.reshape(3,3,1)
array_reshape_2

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [27]:
array_reshape_2.ndim

3

In [29]:
array_reshape_2.shape

(3, 3, 1)

#### Find Mean, Median, Variance, Standard Deviation

In [44]:
np.mean(new_array)

5.0

In [45]:
np.median(new_array)

5.0

In [46]:
np.var(new_array)

6.666666666666667

In [47]:
np.std(new_array)

2.581988897471611

#### Generate Random Values in a Given Range

For np.random.randint(low, high, size), low - inclusive (included), high - exclusive (not included)

In [50]:
np.random.randint(1, 10,3)

array([4, 9, 1])

### enumerate() built-in function

In [111]:
x=np.random.randint(1,100,10)
x

array([92, 75, 99, 35, 22, 47, 90,  2, 41, 91])

In [113]:
y=enumerate(x)

In [115]:
for index,value in y:
    print(index,value)

0 92
1 75
2 99
3 35
4 22
5 47
6 90
7 2
8 41
9 91


In [118]:
text = "Hello, World!"

for index, char in enumerate(text):
    print(index, char)


0 H
1 e
2 l
3 l
4 o
5 ,
6  
7 W
8 o
9 r
10 l
11 d
12 !


- enumerate() can be used with array, string, list, tuple.

### Series

In [8]:
new_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
s1=pd.Series(new_array)
s1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int32

In [18]:
print(s1.ndim)
print(s1.shape)

1
(9,)


In [12]:
s2=pd.Series([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(s2)

0       [1, 2, 3]
1       [4, 5, 6]
2       [7, 8, 9]
3    [10, 11, 12]
dtype: object


In [20]:
print(s2.ndim)
print(s2.shape)

1
(4,)


In [28]:
dictionary = {0: 21, 1: 400, 2: 39, 3: 10}
s3 = pd.Series(data=dictionary)
s3

0     21
1    400
2     39
3     10
dtype: int64

In [38]:
dictionary = {0: 21, 1: 400, 2: 39, 3: 10}
s4 = pd.Series(data=dictionary,index=['w','x','y','z'])
s4

w   NaN
x   NaN
y   NaN
z   NaN
dtype: float64

### describe()

In [47]:
s1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int32

In [42]:
s1.describe()

count    9.000000
mean     5.000000
std      2.738613
min      1.000000
25%      3.000000
50%      5.000000
75%      7.000000
max      9.000000
dtype: float64

### DataFrame

In [22]:
dictionary1={'col1':[10,20],'col2':[30,"Ram"]}
pd.DataFrame(data=dictionary1)

col1 col2
0    10   30
1    20  Ram

In [122]:
data = {"Name": ["Alice", "Bob", "Charlie"],
        "Age": [25, 30, 35],
        "City": ["NY", "LA", "Chicago"]}
pd.DataFrame(data)

Name  Age     City
0    Alice   25       NY
1      Bob   30       LA
2  Charlie   35  Chicago

In [3]:
df=pd.DataFrame(np.array([[100,2000],[200,3000],[250,4000]]),index=["pune","Mumbai","Nagpur"],columns=['max_speed','distance'])
df

max_speed  distance
pune          100      2000
Mumbai        200      3000
Nagpur        250      4000

In [52]:
df.shape

(3, 2)

In [54]:
df.ndim

2

### loc and iloc

- loc stands for Label-based Indexing
- iloc stands for Integer-location Based Indexing

In [58]:
df

max_speed  distance
pune          100      2000
Mumbai        200      3000
Nagpur        250      4000

In [60]:
df.loc[["pune"]]

max_speed  distance
pune        100      2000

In [66]:
df.loc["pune"]

max_speed     100
distance     2000
Name: pune, dtype: int32

In [62]:
type(df.loc[["pune"]])

pandas.core.frame.DataFrame

In [64]:
type(df.loc["pune"])

pandas.core.series.Series

In [68]:
df.loc[["pune","Nagpur"]]

max_speed  distance
pune          100      2000
Nagpur        250      4000

In [70]:
df.loc[["pune","Nagpur"],["distance"]]

distance
pune        2000
Nagpur      4000

In [74]:
df.loc[:,["max_speed"]]

max_speed
pune          100
Mumbai        200
Nagpur        250

In [5]:
df.loc[:,:]

max_speed  distance
pune          100      2000
Mumbai        200      3000
Nagpur        250      4000

In [86]:
df.loc["pune":"Nagpur"]

max_speed  distance
pune          100      2000
Mumbai        200      3000
Nagpur        250      4000

In [80]:
df.loc[:]

max_speed  distance
pune          100      2000
Mumbai        200      3000
Nagpur        250      4000

In [7]:
df

max_speed  distance
pune          100      2000
Mumbai        200      3000
Nagpur        250      4000

In [76]:
df.iloc[[0]]

max_speed  distance
pune        100      2000

In [84]:
df.iloc[0:2]

max_speed  distance
pune          100      2000
Mumbai        200      3000

In [9]:
df.iloc[[0,1]]

max_speed  distance
pune          100      2000
Mumbai        200      3000

In [94]:
df.iloc[[0],0:2]

max_speed  distance
pune        100      2000

In [96]:
df.iloc[0:3]

max_speed  distance
pune          100      2000
Mumbai        200      3000
Nagpur        250      4000